### ISSUE TITLE
Project file support

### ISSUE THREAD

**Issue by RaYell** [mddocs/mddocs#16]

**Comment by RaYell** [comment]
An example project XML

```xml
<project>
  <files>
    <file path="/Foo/Release/Foo.dll"/>
    <file path="/Foo/Release/Foo.xml"/>
  </files>
  <output path="/doc"/>
  <descriptions>
    <assemblies>
      <assembly name="MyAssembly">
        The description for the assembly. 
        Can include VS documentaion <c>tags</c>.
      </assembly>
    </assemblies>
    <namespaces>
      <namespace name="Namespace.Name">The description for the namespace.</namespace>
    </namespaces>
  </descriptions>
  <parameters>
    <parameter name="IncludeNonPublicMembers" value="true"/>
  </parameters>
</project>
```

An example JSON config
```json
{
  "files": [ "/Foo/Release/Foo.dll", "/Foo/Release/Foo.xml" ],
  "output": "/doc",
  "descriptions": {
    "assemblies": {
      "MyAssembly": "The description for the assembly. Can include VS documentaion <c>tags</c>.",
    },
    "namespaces": {
      "Namespace.Name": "The description for the namespace."
    }
  },
  "parameters": {
    "IncludeNonPublicMembers": true
  }
}
```

**Comment by RaYell** [comment]
An example YAML config

```yml
files:
  - /Foo/Release/Foo.dll
  - /Foo/Release/Foo.xml
output: /doc
descriptions:
  assemblies:
    MyAssembly: "The description for the assembly. Can include VS documentaion <c>tags</c>."
  namespaces:
    Namespace.Name: "The description for the namespace."
parameters:
  IncludeNonPublicMembers: true
```
